const SOURCE_EXTS = new Set([
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".mjs",
  ".cjs",
  ".json",
  ".md",
  ".mdx",
  ".prisma",
]);

const IGNORED_DIRS = new Set([
  "node_modules",
  ".git",
  ".devlens",
  ".next",
  "dist",
  "build",
  "coverage",
  ".turbo",
  ".vercel",
  "out",
]);

const IGNORED_PATH_SEGMENTS = [
  "generated",
  "src/generated",
  "prisma/generated",
];

const CONFIG_FILE_CANDIDATES = [
  "package.json",
  "tsconfig.json",
  "tsconfig.app.json",
  "tsconfig.node.json",
  "jsconfig.json",
  "vite.config.js",
  "vite.config.ts",
  "next.config.js",
  "next.config.mjs",
  "next.config.ts",
  "webpack.config.js",
  "webpack.config.ts",
  "rollup.config.js",
  "rollup.config.ts",
  "esbuild.config.js",
  "esbuild.config.ts",
  "eslint.config.js",
  "eslint.config.mjs",
  ".eslintrc",
  ".eslintrc.json",
  ".eslintrc.js",
  ".eslintrc.cjs",
  ".prettierrc",
  ".prettierrc.json",
  ".prettierrc.js",
  "prettier.config.js",
  "prettier.config.cjs",
  "tailwind.config.js",
  "tailwind.config.ts",
  "postcss.config.js",
  "postcss.config.cjs",
  "babel.config.js",
  "babel.config.cjs",
  "jest.config.js",
  "jest.config.ts",
  "vitest.config.js",
  "vitest.config.ts",
  "playwright.config.ts",
  "cypress.config.ts",
  "prisma/schema.prisma",
];

module.exports = {
  SOURCE_EXTS,
  IGNORED_DIRS,
  IGNORED_PATH_SEGMENTS,
  CONFIG_FILE_CANDIDATES,
};
