const path = require("path");
const { fsp, root, pathExists } = require("./utils");

const START_MARKER = "<!-- devlens:start -->";
const END_MARKER = "<!-- devlens:end -->";

const AGENT_FILES = [
  "CLAUDE.md",
  "AGENTS.md",
  "GEMINI.md",
  ".cursorrules",
  ".github/copilot-instructions.md",
  ".windsurfrules",
];

function buildBlock(manifest) {
  return [
    START_MARKER,
    "## Project structure",
    "",
    "_Auto-generated by devlens — do not edit by hand. Run `devlens push` to refresh._",
    "",
    "```json",
    JSON.stringify(manifest, null, 2),
    "```",
    END_MARKER,
  ].join("\n");
}

function injectBlock(existing, block) {
  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + END_MARKER.length);
    return before + block + after;
  }

  const trimmed = existing.replace(/\s*$/, "");
  return trimmed.length > 0 ? `${trimmed}\n\n${block}\n` : `${block}\n`;
}

async function findAgentFiles() {
  const found = [];
  for (const rel of AGENT_FILES) {
    if (await pathExists(path.join(root, rel))) {
      found.push(rel);
    }
  }
  return found;
}

async function push(manifest, targetArg) {
  const block = buildBlock(manifest);

  let targets;
  if (targetArg) {
    targets = [targetArg];
  } else {
    targets = await findAgentFiles();
    if (targets.length === 0) {
      const err = new Error(
        "no agent file found in this project.\n" +
          `  Looked for: ${AGENT_FILES.join(", ")}\n` +
          "  Create one of those files, or run: devlens push --target <file>",
      );
      throw err;
    }
  }

  const written = [];
  for (const rel of targets) {
    const full = path.resolve(root, rel);

    const next = injectBlock(await fsp.readFile(full, "utf8"), block);
    await fsp.mkdir(path.dirname(full), { recursive: true });
    await fsp.writeFile(full, next, "utf8");
    written.push(rel);
  }

  return written;
}

module.exports = {
  push,
  buildBlock,
  injectBlock,
  findAgentFiles,
  AGENT_FILES,
  START_MARKER,
  END_MARKER,
};
